### ISSUE TITLE
[Feature Request] Support instance to be stopped instead of terminated

### ISSUE THREAD

**Issue by duanshiqiang** [GoogleCloudPlatform/compute-jenkins-plugin#1]
It would be good if this plugin supports stop the instance after idle time instead of terminate it. For some kind of build job, reuse namespace and save new instance set up time is quite important to reduce build time.

AWS EC2 Plugin supports this and it would be good if GCE can also supports this.

**Comment by evandbrown** [comment]
Hi Duan,
Thanks for opening this issue. I wanted to let you know that this repository has been forked to https://github.com/jenkinsci/google-compute-engine-plugin and we'll be maintaining it from there.

The Jenkins team uses JIRA for issue tracking. It'd be great if you could head to https://issues.jenkins-ci.org and create a new issue under the `google-compute-engine-plugin` component.

Thanks!
